version: '3.7'

services:
  postgreslocagames:
    image: postgres:16
    container_name: postgres-loca-games
    restart: always
    environment:
      POSTGRES_DB: locagames
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: